# Generated by Django 5.0.4 on 2024-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_historey',
            name='title',
            field=models.CharField(default='string', max_length=5000),
        ),
    ]
