# Generated by Django 5.0.4 on 2024-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_video_historey_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_historey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('title', models.CharField(default='string', max_length=5000)),
            ],
        ),
    ]
